---
- name: "rpm-ostree: Reload rpm-ostree configuration"
  ansible.builtin.command:
    cmd: rpm-ostree reload
  become: yes

- name: "rpm-ostree: Enable timer"
  ansible.builtin.systemd:
    name: rpm-ostreed-automatic.timer
    state: started
    enabled: yes
    daemon_reload: yes
  become: yes
