---
- name: "services: Apply rpm-ostree changes live"
  ansible.builtin.command:
    cmd: rpm-ostree ex apply-live
  become: yes
  when: services_rpm_ostree_applyLive | bool

- name: "chrony: Restart service"
  ansible.builtin.systemd:
    name: chronyd
    state: restarted
    enabled: yes
  become: yes

- name: "snapper: Enable timers"
  ansible.builtin.systemd:
    name: "{{ item }}"
    state: started
    enabled: yes
  with_items:
    - snapper-cleanup.timer
    - snapper-timeline.timer
  become: yes

- name: "libvirtd: Enable service"
  ansible.builtin.systemd:
    name: libvirt.service
    state: started
    enabled: yes
  become: yes

- name: "flatpak: Enable timer"
  ansible.builtin.systemd:
    name: flatpak-automatic.timer
    state: started
    enabled: yes
    daemon_reload: yes
  become: yes