---
- name: Include remotes.yml
  ansible.builtin.include: remotes.yml
  when: flatpak_configure_remotes | bool

- name: Include flatpaks.yml
  ansible.builtin.include: flatpaks.yml
  when: flatpak_alter_flatpaks | bool

# https://github.com/flatpak/flatpak/issues/3847#issuecomment-818532856
- name: Enable flatpak Automatic Update
  ansible.builtin.template:
    src: "{{ item }}"
    dest: "/etc/systemd/system/{{ item | regex_replace('.j2', '') }}"
    owner: root
    group: root
    mode: '0644'
  become: yes
  with_items:
    - flatpak-automatic.service.j2
    - flatpak-automatic.timer.j2
  notify:
    - Enable flatpak-automatic
  when: flatpak_automatic_updates | bool
