---
# these list are only for role internal tasks
# this is needed for constructing a package list
# to vastly reduce installation time
rpm_ostree_layeredPackages_removalList: []
rpm_ostree_layeredPackages_installList: []

rpm_ostree_enable: true
rpm_ostree_autoUpdate: true
rpm_ostree_modifyBasePackages: true
rpm_ostree_modifyLayeredPackages: true
rpm_ostree_modifyKargs: true
rpm_ostree_basePackages:
  firefox:
    state: absent
rpm_ostree_layeredPackages:
  ansible:
    state: present
rpm_ostree_kargs:
  'rd.luks.options=discard':
    state: present