---
- name: "sysctl: Change settings"
  ansible.posix.sysctl:
    name: "{{ item.key }}"
    value: "{{ item.value.value }}"
    state: "{{ item.value.state }}"
    sysctl_file: "/etc/sysctl.d/100-custom.conf"
    sysctl_set: yes
  become: yes
  loop: "{{ lookup('dict', config_sysctl_params, wantlist=True) }}"
