---
- name: "config: Update user shell"
  ansible.builtin.user:
    name: "{{ item.key }}"
    shell: "{{ item.value.shell }}"
  become: yes
  loop: "{{ lookup('dict', config_users, wantlist=True) }}"
