---
config_hostname: ice9

config_fstab_entries_overrides:
  root:
    src: UUID=aa63fb86-3fc9-42d1-82ca-7d47d0238765
  home:
    src: UUID=aa63fb86-3fc9-42d1-82ca-7d47d0238765
  docker:
    src: UUID=aa63fb86-3fc9-42d1-82ca-7d47d0238765

services_flatpak_packages_overrides:
  com.github.Bleuzen.FFaudioConverter:
    state: present
    remote: flathub
  com.snes9x.Snes9x:
    state: present
    remote: flathub
#  com.valvesoftware.Steam.CompatibilityTool.Proton:
#    state: present
#    remote: flathub
  io.mgba.mGBA:
    state: present
    remote: flathub
  io.openrct2.OpenRCT2:
    state: present
    remote: flathub
  org.gnome.Firmware:
    state: absent
    remote: flathub
  org.kde.kid3:
    state: present
    remote: flathub
  org.musicbrainz.Picard:
    state: present
    remote: flathub

rpm_ostree_layeredPackages_overrides:
  radeontop:
    state: present
