---
etc_hostname: vinci

etc_fstab_entries_overwrite:
  root:
    src: UUID=9296ebbe-a288-48e4-a9cd-0a80374c7c46
  home:
    src: UUID=9296ebbe-a288-48e4-a9cd-0a80374c7c46
  docker:
    src: UUID=9296ebbe-a288-48e4-a9cd-0a80374c7c46

flatpak_flatpaks_overwrite:
  com.discordapp.Discord:
    state: absent
    remote: flathub
  com.mattermost.Desktop:
    state: present
    remote: flathub
  com.valvesoftware.Steam:
    state: present
    remote: flathub
  im.riot.Riot:
    state: absent
    remote: flathub
  org.chromium.Chromium:
    state: absent
    remote: flathub
  org.gnome.Evolution:
    state: absent
    remote: fedora
  org.gnome.Firmware:
    state: present
    remote: flathub

rpm_ostree_layered_packages_overwrite:
  radeontop:
    state: absent
